<?php
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// There's almost certainly a better way to include the facebook php sdk here,
// but this tab is small enough and on a tight enough schedule that this works.
require_once 'settings.local.php';
require_once 'l10n_moz.class.php';
require_once 'lib/facebook-php-sdk/src/facebook.php';

define('LOCALE_DIR', 'locales');
define('LANG_FILE', 'olympics.lang');
define('REGION_DIR', 'regions');

/**
 * Given a requested language, returns the best supported language available.
 */
function get_supported_language($lang) {
    // Build a list of valid locales.
    $locales = array_diff(scandir(LOCALE_DIR), array('.', '..'));

    // Validate requested language against available languages.
    if (!in_array($lang, $locales)) {
        // Maintain a special mapping between certain Facebook locales and
        // Mozilla ones.
        $fb_language_map = array(
            'es-LA' => 'es-ES'
        );
        if (array_key_exists($lang, $fb_language_map)) {
            return $fb_language_map[$lang];
        }

        // Mozilla locales are weird, attempt to match by just the first part of
        // the locale code.
        $lang = substr($lang, 0, strpos($lang, '-'));
        if (!in_array($lang, $locales)) {
            return 'en-US';
        }
    }

    return $lang;
}

// Retrieve the requested locale, defaulting to en-US.
$facebook = new Facebook(array(
    'appId' => FB_APP_ID,
    'secret' => FB_APP_SECRET
));
$signed_request = $facebook->getSignedRequest();
if ($signed_request !== null) {
    $lang = strtr($signed_request['user']['locale'], '_', '-');
} else {
    // We're not in a Facebook page, so let's see if there's a lang parameter.
    $lang = (array_key_exists('lang', $_GET) ? $_GET['lang'] : 'en-US');
}
$lang = get_supported_language($lang);

// Read in locale data and set up translation function.
$l10n = new l10n_moz();
l10n_moz::load(sprintf('%s/%s/%s', LOCALE_DIR, $lang, LANG_FILE));
function ___($key) {
    global $l10n;
    return $l10n->get($key);
}

// Load region name JSON file.
$region_lang = $lang;
$region_files = array_diff(scandir(REGION_DIR), array('.', '..'));
if (!in_array($lang . '.json', $region_files)) {
    $region_lang = 'en-US';
}
$json = file_get_contents(sprintf('%s/%s.json', REGION_DIR, $region_lang));
$region_names = json_decode($json, true);
function get_region_name($region_code) {
    global $region_names;
    if (array_key_exists($region_code, $region_names)) {
        return $region_names[$region_code];
    } else {
        return $region_code;
    }
}

$personas = array(
    'ch' => array('persona' => '{"id":"475238","name":"Switzerland Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/8\/475238\/Persona_Switzerland.jpg?1342126352","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/8\/475238\/footer_persona_Switzerland.jpg?1342126352","detailURL":"http:\/\/www.getpersonas.com\/persona\/475238","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/8\/475238\/preview.jpg?1342126352","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/8\/475238\/preview_small.jpg?1342126352","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFAABAAAAAAAAAAAAAAAAAAAACP\/EACIQAAICAQQCAwEAAAAAAAAAAAECAwQFBhESIQBBBwgTUf\/EABUBAQEAAAAAAAAAAAAAAAAAAAYH\/8QAKBEAAQMCBAQHAAAAAAAAAAAAAQIDEQAEBQYhMRIUQVEVImFxgbHh\/9oADAMBAAIRAxEAPwBRa++uC3cTp3IfGGJtSteiMl437gjKBkRkZuW3HbdlIC77+vAV9lsONtLsEkyNZMbwRP4KsuD59LL9w1jLgHCYTwpmYJBAiZ6GSaPGqcFa0zmr+ncpCiXcdYeCbg5KhlPex63B9H+EeD7q3VauqZcHmSYNU\/DrxGI26LtkyhYBHz9Ul8l9iRqb4XyeSl1RS05rD95I61emzfo4V1ZQgbkQGjJXkfYPY8brzFzWFrWXA29JgD0I233HXvUkayN4fmFtlLKnrWASVRAkEGYgaK1jt3ou5W7ezF6XI5LIT3bdl+cs87l3kPXbE9k7eBXlreWVuKknqd6sVsy3atBplASlOwGgHsK\/\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475238","version":"1342126352"}'),
    'co' => array('persona' => '{"id":"475369","name":"Flag of Columbia","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/9\/475369\/Persona_columbia.jpg?1342204173","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/9\/475369\/footer_persona_columbia.jpg?1342204173","detailURL":"http:\/\/www.getpersonas.com\/persona\/475369","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/9\/475369\/preview.jpg?1342204173","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/9\/475369\/preview_small.jpg?1342204173","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAABAYHCP\/EACQQAAIBAwQABwAAAAAAAAAAAAEDAgAEBQYREiEHQVGBobHR\/8QAGAEAAgMAAAAAAAAAAAAAAAAABgcBAgP\/xAAoEQABAwMBBgcAAAAAAAAAAAABAgMRAAQFBgcSIVORkhQxQWFiosH\/2gAMAwEAAhEDEQA\/AJ7j7HUWUYFpRcO9AtRmfrqsL7admFzDiGR8UieqpNNK12D6CwiQrIlTxHNdgdqNz9ptx\/hVrDINgI4l0QRvu+Qh8UDZPXK7mfFXS3PaSR04CiexRofTYjGWzaSOW0Ce4iftWn7PA22PiIrSlQ6PFaxGI9h50mFurcO8eNL\/AHRMnzowpgmUeK+Z26EY\/tUiPWpr\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475369","version":"1342204173"}'),
    'cn' => array('persona' => '{"id":"474690","name":"China Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/0\/474690\/Persona_china3.jpg?1341604870","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/0\/474690\/footer_persona_china2.jpg?1341604870","detailURL":"http:\/\/www.getpersonas.com\/persona\/474690","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/0\/474690\/preview.jpg?1341604870","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/0\/474690\/preview_small.jpg?1341604870","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgQGB\/\/EACQQAAEEAgECBwAAAAAAAAAAAAECAwQRACEUBTESEyIjMmGh\/8QAGQEAAgMBAAAAAAAAAAAAAAAAAwQAAgcI\/8QAIhEAAQMDAwUAAAAAAAAAAAAAAQACEQMSIQRBcSIxMlFh\/9oADAMBAAIRAxEAPwDE+omJH4XI9yVxUKddMkSA4lQtsCvgUppJSTYI3XbM80jg68sw2SALbYI8uZOQd\/vddqUKR6nsMCfUc8yczupnqsly0+WfTvQGsfYAUPV3sdLU5EIGyEFJFjxDv+ZC1FpaoPwjfajOK0G170KNfeUmE0Kbawyv\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/474690","version":"1341604870"}'),
    'cl' => array('persona' => '{"id":"475113","name":"Chile Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/3\/475113\/Persona_Chile.jpg?1342038667","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/3\/475113\/footer_persona_CH.jpg?1342038667","detailURL":"http:\/\/www.getpersonas.com\/persona\/475113","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/3\/475113\/preview.jpg?1342038667","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/3\/475113\/preview_small.jpg?1342038667","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAACQYH\/8QAJxAAAgEDAgQHAQAAAAAAAAAAAQIDBAYRAAUHEhRBCCEkUWJxgZH\/xAAZAQACAwEAAAAAAAAAAAAAAAAABgMEBQj\/xAAnEQABAwIEBQUAAAAAAAAAAAABAAIDBREEEiGRBgciQYExMmJxov\/aAAwDAQACEQMRAD8AUww4fnGQe\/noQp+7L+sWxoTVXhd+0bMirn1tYkTMPipPMfwHUUs8UIvI4D7WrTaHU6w7JgIHyH4tJ3PoPJRq3d4nOPN6c67rxDraSlkUjptsxRRlfbMQDsPtjpPlqOKm9z9tF2BTOXvDFJsYMK1zh3f1n9XA8ALKKyYz1L1c8vUTuctJKWd2PfLE5P8AdUXG5uU7xMyMDGizR2FgNhov\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475113","version":"1342038667"}'),
    'ca' => array('persona' => '{"id":"475403","name":"Flag of Canada","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/0\/3\/475403\/Persona_canada.jpg?1342218245","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/0\/3\/475403\/footer_persona_canada.jpg?1342218245","detailURL":"http:\/\/www.getpersonas.com\/persona\/475403","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/0\/3\/475403\/preview.jpg?1342218245","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/0\/3\/475403\/preview_small.jpg?1342218245","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAACQcI\/8QAKRAAAQMCBAMJAAAAAAAAAAAAAQIDBAYRAAUHIRIxQQgTFBUkMnGBkf\/EABcBAAMBAAAAAAAAAAAAAAAAAAUGBwj\/xAAoEQABAQYFAwUAAAAAAAAAAAABAgADBAURIQYSMUFRExUiQnGRseH\/2gAMAwEAAhEDEQA\/AL\/pLpVUNP0PVDmpUKYxmlYSHUTIkx3iAQUqSHFG5uVlxRJ6Dpe+BUuhVodL62qtQ1HxxiKEipjD9rILtwAUqTa9QaDgCgH42AKkkTMiel5aqJC8U1LcYcdEHvAhaFWUkLXcC2\/IYDHwqN2qiCYkpepUcpAIvsbiwZk6hhJej+XpBDaEBtIO\/IbXPM\/OG3SzZmUSo5juxWdqWh3KU1uqXL0j0015GZsJPt4H0hSvxYWPrCjMiXMSoc3+W03gMJmsgh3vqSCg+6TT6o3\/2Q==","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475403","version":"1342218245"}'),
    'it' => array('persona' => '{"id":"475015","name":"Flag Italy","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/5\/475015\/Persona_Italy.jpg?1341943165","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/5\/475015\/footer_persona_italy.jpg?1341943165","detailURL":"http:\/\/www.getpersonas.com\/persona\/475015","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/5\/475015\/preview.jpg?1341943165","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/5\/475015\/preview_small.jpg?1341943165","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwUGB\/\/EACQQAAEDAwMEAwAAAAAAAAAAAAECBBEAAwYFEhMHMmFxkZLh\/8QAGAEAAwEBAAAAAAAAAAAAAAAAAAYIAgT\/xAAnEQABAwEGBgMAAAAAAAAAAAABAAIDEQQFBhJBUQcTIjGRoYGi0v\/aAAwDAQACEQMRAD8AgNd6p5rlV0rznPtRep3duov1L+qCSB8UkGWac9RJ8lWDM24MLsrJJDZvljD+j7SR\/nOLtLnE2c3nh2wE2m5ifBVAHut8mQ6USVeHFzBt3Ag2l0zto2Od9nZW+1nJY8RF3YlJIkEJj9rqqSolc4yOznvvr5RTYFhaYlZUJkJooihov\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475015","version":"1341943165"}'),
    'vn' => array('persona' => '{"id":"475365","name":"Flag of Vietnam","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/5\/475365\/Persona_vietnam.jpg?1342203965","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/5\/475365\/footer_persona_vietnam.jpg?1342203965","detailURL":"http:\/\/www.getpersonas.com\/persona\/475365","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/5\/475365\/preview.jpg?1342203965","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/5\/475365\/preview_small.jpg?1342203965","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABAYH\/8QAJBAAAgIABQMFAAAAAAAAAAAAAQIDBAAFETFhEiFBBhQicaH\/xAAYAQACAwAAAAAAAAAAAAAAAAACCAAEBf\/EACMRAQABAgUEAwAAAAAAAAAAAAECAAMEERIhMRMUYXFBUaH\/2gAMAwEAAhEDEQA\/ANBuyZBFcaTJksx1VHSvuWDO3J0AA+v3C74Huiwd8xbnzpEDwZub7\/KZ3DQvlsb6avGx6qW9Q3bCOhhb4nXxvjSsxE3ocRKUXam0sxSaRmKIA5J6QOw1Ow4wHQbcQ5y+6lq8IRz4pMtWnaOyNoew584BkwasEC5zX\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475365","version":"1342203965"}'),
    'cz' => array('persona' => '{"id":"475114","name":"Czech Republic Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/4\/475114\/Persona_Czech.jpg?1342039275","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/4\/475114\/footer_persona_CZ.jpg?1342039275","detailURL":"http:\/\/www.getpersonas.com\/persona\/475114","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/4\/475114\/preview.jpg?1342039275","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/4\/475114\/preview_small.jpg?1342039275","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwYICf\/EACUQAAECBQMEAwAAAAAAAAAAAAECAwAEBhEhBQcSEyIygUGRsf\/EABcBAQEBAQAAAAAAAAAAAAAAAAQGBQj\/xAAnEQABAgQEBgMAAAAAAAAAAAABAgUAAwRBETFR8AYSEyFxoRSR0f\/aAAwDAQACEQMRAD8Av6iN36B3F0hFS0hUcvMsGweQpfTdYVbwdbVlCvVj8EiF1zfUNszpVKcD6Pg33jAm9xp3SV1aVXMLi48jMbwhlOuyZ4uCcaIIOeoMj7gfaH8qtD9Ri2jUX21cy4CFJtckgkeok3R0rXmf8itmFRsMgBoBkBsx1Zw0wMnCFGG9nkCWm5zUo6rUe6j6FgBA3NW7+17lnA5Kt+xllGEVMuqChh+R\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475114","version":"1342039275"}'),
    'ar' => array('persona' => '{"id":"474681","name":"Flag Argentina","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/1\/474681\/Persona_argentina1a.jpg?1341599107","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/1\/474681\/footer_persona_argentina.jpg?1341599107","detailURL":"http:\/\/www.getpersonas.com\/persona\/474681","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/1\/474681\/preview.jpg?1341599107","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/1\/474681\/preview_small.jpg?1341599107","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABAUI\/8QAJBAAAQMEAQMFAAAAAAAAAAAAAQIEEQADBQYhBxIxEyIjQaL\/xAAYAQACAwAAAAAAAAAAAAAAAAAEBgMFB\/\/EACQRAAEEAQIGAwAAAAAAAAAAAAEAAgMEERIxBQYHISLwgZHh\/9oADAMBAAIRAxEAPwDX2sstQvul3c\/k77MeZb9xJEfYANJPTNvEWV3uYzwO3vZWvNhpOcBK7DkDcG3Tm1dQGeyZXtMz8J5\/FasZLw3YPv8AUlCKidnn34R7TX0Ux7VBQ8r5JFG1qkFOMRQNwAgJ7Mtl+uU5U5\/iWjlUqShUHgQYonTlQasFf\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/474681","version":"1341599107"}'),
    'gb' => array('persona' => '{"id":"475013","name":"Great Britain Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/3\/475013\/Persona_GB1a.jpg?1341942981","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/3\/475013\/footer_persona_gb.jpg?1341942981","detailURL":"http:\/\/www.getpersonas.com\/persona\/475013","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/3\/475013\/preview.jpg?1341942981","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/3\/475013\/preview_small.jpg?1341942981","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABwAD\/8QAJhAAAAUDAwMFAAAAAAAAAAAAAQIDBAUGBxEAEiEIIkETI1Jykf\/EABYBAQEBAAAAAAAAAAAAAAAAAAUHBP\/EAC8RAAECAwYEAwkAAAAAAAAAAAECAwQFEQAGEhRBYQchcbETMUIWIiU0Q4GCkcH\/2gAMAwEAAhEDEQA\/AEuuZSvTNIyQq+31pqNjoVMWEeWcepHTZBwJkwRUVUAqg8Cb2t4+c6xSly8byCxKkYRqE0qOutq7PILhvCRGcn0W7EOL51IVRW6aJSCOhpp5CxfVNy5FJMrZx1MMmjbAgZjR0WqmmYPjkpGyY\/ohpP2RvLGnFGO06qJ7WHVxG4eSf3ZPLMZGqgkd8dqF6kJdZVWPvTRzCqNxTN1pZqBY+Z2lHaIHUIT0XQBgexZMQHnI6ocfcqBiV5mAUWXNCkn+GvcbWjkqv\/NZcxkYuj8Pq24AtP2B5A7pwne2ziy9lbyLmPZ2r2J5ZXuJCOiFjpDOR4BqqcG7nHkW6qX1HR6o+8cgHxBrMND1CgV+\/I\/kEneyqYK595vknTAvn0qq4yTt9RA6eIBb\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475013","version":"1341942981"}'),
    'in' => array('persona' => '{"id":"475043","name":"Flag India","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/3\/475043\/Persona_india.jpg?1341968417","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/3\/475043\/footer_persona_india.jpg?1341968417","detailURL":"http:\/\/www.getpersonas.com\/persona\/475043","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/3\/475043\/preview.jpg?1341968417","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/3\/475043\/preview_small.jpg?1341968417","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwUGB\/\/EACYQAAIBAwMCBwEAAAAAAAAAAAECAwQREgAFBgchCBMjMkFhgZH\/xAAXAQADAQAAAAAAAAAAAAAAAAAEBQcD\/8QAJxEAAgAFAwEJAAAAAAAAAAAAAQIAAwQREgYhMZEFFyIyQWHR4fL\/2gAMAwEAAhEDEQA\/AGfHuadE6DcIW3fbN\/ZHelnxpa0OwAlBqHNm9vlEqB2DE\/Gk\/bNNptaV50yU6qFZSccL5eVADa7A+IWuVsSTtANPr+tpmDFybFW3F9xzyfUbEcH2ih5R1O8LaFG27i\/NFRib54G\/9kOpqlJpY8S5vX7h73sVj\/gfMYVRSSRsX9IpItxktiw\/B30pqGnzTlOctbjIk9LxHmRgbmBVkdHJNbCOQ3uoxOP3oNnw3EYk47iP\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475043","version":"1341968417"}'),
    'id' => array('persona' => '{"id":"475016","name":"Flag of Indonesia","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/6\/475016\/Persona_indonesia.jpg?1341943203","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/6\/475016\/footer_persona_indonesia.jpg?1341943203","detailURL":"http:\/\/www.getpersonas.com\/persona\/475016","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/6\/475016\/preview.jpg?1341943203","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/6\/475016\/preview_small.jpg?1341943203","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFQABAQAAAAAAAAAAAAAAAAAABgn\/xAAjEAABAwMCBwAAAAAAAAAAAAABAgMFAAQGCCESMTdRYaLC\/8QAGAEAAwEBAAAAAAAAAAAAAAAAAAUHAgT\/xAAjEQACAQIEBwAAAAAAAAAAAAAAAQIDBAUHMdEyQlKCkZKh\/9oADAMBAAIRAxEAPwBPIaJJ63HUCN27WLoI9qRLB59a8FklmlbS0tZey2A2Q6VpyOeDQzSyWfFk4PqtrCWub4cdXMqlPht5LuWxRKZhwsqSG9+VOiTgeSwxq7c4ltAkGgD\/2Q==","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475016","version":"1341943203"}'),
    'es' => array('persona' => '{"id":"475042","name":"Flag of Spain","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/2\/475042\/Persona_spain.jpg?1341968151","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/2\/475042\/footer_persona_spain.jpg?1341968151","detailURL":"http:\/\/www.getpersonas.com\/persona\/475042","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/2\/475042\/preview.jpg?1341968151","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/2\/475042\/preview_small.jpg?1341968151","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABwUG\/8QAJhAAAgEBBwMFAAAAAAAAAAAAAQIDBAAFBgcREiEiMUEIFBVhgf\/EABcBAAMBAAAAAAAAAAAAAAAAAAUGBwD\/xAAqEQACAAQEAgsAAAAAAAAAAAABEQACAwQFEiExBlETFCIyQVRhkaHS4v\/aAAwDAQACEQMRAD8AUL3xrlqsEl7YpwZ8qqVIp5J52Mjs0gaUxhw46VUJxxx2Pi0\/xClfYnR6zZz5dkzMNWWTl9EA3zQMWSxwbEjWkpWlYSEjMANB2VKyFuSTqHrvB7iPHvp\/V0lp8nYkDFtwEHf9MtgAwvibzMnvN9YOVML4lkKN58\/mMu1bevsVu6apSWjErVKLKvUzsNpbdpqdQAOT4s7CWUJSh7Nark+UOtPDbWncm7pgicyiVM5UC+60C\/EbxBvCkpHl1AikOvC7Tt+7ZqCAt+kGsf\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475042","version":"1341968151"}'),
    've' => array('persona' => '{"id":"475366","name":"Flag of Venezuela","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/6\/475366\/Persona_venezuela.jpg?1342204008","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/6\/475366\/footer_persona_venezuela.jpg?1342204008","detailURL":"http:\/\/www.getpersonas.com\/persona\/475366","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/6\/475366\/preview.jpg?1342204008","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/6\/475366\/preview_small.jpg?1342204008","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABAUH\/8QAJhAAAQIEBQQDAAAAAAAAAAAAAQIDAAQRIQcIEjFBBQYTFlFhkv\/EABkBAAIDAQAAAAAAAAAAAAAAAAEHAgMFCP\/EACQRAAEDAQgDAQAAAAAAAAAAAAEAAgMGBAUHESExk9IXVoPR\/9oADAMBAAIRAxEAPwA7uZnFokL9vm0bE6PFcfiF6Kdw8G9Ow8kvZO3wDez9RUMvBH2Unq+ZfGV3SpnvWdauaBCG6FPFap3+4Lacw99eh5Jf1B+A17xbVBIfhH2WYSk2pdyoEEWrzE3NyXRFntLXgBIUlpxVNIPxa0Vk5LQa0P0IX\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475366","version":"1342204008"}'),
    'nl' => array('persona' => '{"id":"475364","name":"Netherlands Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/4\/475364\/Persona_netherlands.jpg?1342203876","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/4\/475364\/footer_persona_netherlands.jpg?1342203876","detailURL":"http:\/\/www.getpersonas.com\/persona\/475364","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/4\/475364\/preview.jpg?1342203876","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/4\/475364\/preview_small.jpg?1342203876","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAAAwYHCf\/EACkQAAEDAgQDCQAAAAAAAAAAAAECAwUABAYHEzEREkEIFCEiQnFyg6H\/xAAYAQACAwAAAAAAAAAAAAAAAAAABgQFB\/\/EACIRAAEEAQIHAAAAAAAAAAAAAAEAAgQRAwWRITEyYXHB4f\/aAAwDAQACEQMRAD8AQYuLz8ziu1XTkVjXFHNwAefZuLgHqCFueRI36gVpzskKCKtrNh9SSxsmVxpzt1TYXscZ4TTiO8x8TAMLRvKSDZWPraDhH5Vbl1+Dj5EuPYezSmY9Jkv6gB5K0KXqWqNK5uSdiG0g8oHxHGkOk0oSy0i4SnSUpSk+hvw9iTQhf\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475364","version":"1342203876"}'),
    'pt' => array('persona' => '{"id":"475651","name":"Flag of Portugal","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/1\/475651\/Persona_portugal.jpg?1342472956","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/1\/475651\/footer_persona_portugal.jpg?1342472956","detailURL":"http:\/\/www.getpersonas.com\/persona\/475651","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/1\/475651\/preview.jpg?1342472956","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/1\/475651\/preview_small.jpg?1342472956","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABwUG\/8QAJBAAAgICAQEJAAAAAAAAAAAAAQIDEQUhAAQGBxITFDFCUWH\/xAAZAQABBQAAAAAAAAAAAAAAAAAEAgUGBwj\/xAAlEQACAQIFAwUAAAAAAAAAAAABAhEAAwQFEiFBEzFRFGFxkfD\/2gAMAwEAAhEDEQA\/ACfvPwCdm8sI43gkhmErQskYTzY1coslKaHiomhr6sb5XmEvJce5bQ6ghifP4R91r7JczfNLDkhgV0zJkgldRSedPbffg0XZAOxVo0KmyDV8c1jmlYoFjKA1v8p6vrpWm6ljIxACl1+I0AKFAfg4BaUWxC1KvSWMOnSsrpHt5Pcnkk+TvUCfGqXIUg79t1wgOBQDYNnECQPmv\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475651","version":"1342472956"}'),
    'tw' => array('persona' => '{"id":"475357","name":"Taiwan Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/7\/475357\/Persona_taiwan.jpg?1342202634","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/7\/475357\/footer_persona_taiwan.jpg?1342202634","detailURL":"http:\/\/www.getpersonas.com\/persona\/475357","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/7\/475357\/preview.jpg?1342202634","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/7\/475357\/preview_small.jpg?1342202634","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABgQF\/8QAIBAAAgICAgIDAAAAAAAAAAAAAQIDEQAEEiEFIjFRkf\/EABkBAAIDAQAAAAAAAAAAAAAAAAIFAAEDCP\/EABwRAAICAwEBAAAAAAAAAAAAAAABAhEDBCExkf\/aAAwDAQACEQMRAD8ABtPp6jGZUiUkcjwlYAj6oYm8O8XgnN3b+II+f3ZDIjxIqCzYUsb\/AHLXTLZc8bqLs3Ako9nZWDDrl8kYI6ai1SINvV15HshH76FGslgPWWRdP\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475357","version":"1342202634"}'),
    'tr' => array('persona' => '{"id":"475367","name":"Flag of Turkey","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/7\/475367\/Persona_turkey.jpg?1342204062","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/7\/475367\/footer_persona_turkey.jpg?1342204062","detailURL":"http:\/\/www.getpersonas.com\/persona\/475367","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/7\/475367\/preview.jpg?1342204062","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/7\/475367\/preview_small.jpg?1342204062","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAAAwQH\/8QAIhAAAQMEAgIDAAAAAAAAAAAAAQIEEQADBSEHEgYiE0Fh\/8QAGQEAAgMBAAAAAAAAAAAAAAAAAwQAAQcI\/8QAIhEAAQMEAAcAAAAAAAAAAAAAAQACAwQFESESMUFRYXHB\/9oADAMBAAIRAxEAPwAfPmnG+KzllHHuXdZDHlqg31urZSUOCPZCRAHUagyqZO9Vn9UIGvxCcj6uuLI+5y05dc2Bj86wdcPQnz30PSz3NPLqVI+I+pnUUOMA807VOcw6VbFwkxPUgjXb7qFmFcdSHaTXrDW+rQQvehuP2h5LU0IxKNr\/2Q==","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475367","version":"1342204062"}'),
    'ng' => array('persona' => '{"id":"475117","name":"Nigeria Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/7\/475117\/Persona_nigeria.jpg?1342039512","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/7\/475117\/footer_persona_nigeria.jpg?1342039512","detailURL":"http:\/\/www.getpersonas.com\/persona\/475117","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/7\/475117\/preview.jpg?1342039512","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/7\/475117\/preview_small.jpg?1342039512","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFQABAQAAAAAAAAAAAAAAAAAABgX\/xAAdEAACAQQDAAAAAAAAAAAAAAABAhEAAwQhBRIi\/8QAFwEBAQEBAAAAAAAAAAAAAAAABAUGCP\/EABsRAAICAwEAAAAAAAAAAAAAAAABAgMEESFB\/9oADAMBAAIRAxEAPwATnpZAdbfbsNmYisFFbOca+sJ8s7oWQqp1PrVLrRYxY+ibKYMsgxFDiyLXtEHksS5fXyxNKhIrY9jP\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475117","version":"1342039512"}'),
    'th' => array('persona' => '{"id":"475361","name":"Thailand Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/1\/475361\/Persona_thailand.jpg?1342203709","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/1\/475361\/footer_persona_thailand.jpg?1342203709","detailURL":"http:\/\/www.getpersonas.com\/persona\/475361","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/1\/475361\/preview.jpg?1342203709","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/1\/475361\/preview_small.jpg?1342203709","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABwQI\/8QAJRAAAgEDAwIHAAAAAAAAAAAAAQIDBAYRAAUHCHEJEjEzQVGR\/8QAGQEAAgMBAAAAAAAAAAAAAAAABQgDBAYH\/8QAKhEAAgAEAwUJAAAAAAAAAAAAAQIAAwQFERKRBgchYaETIjFBUWJyseH\/2gAMAwEAAhEDEQA\/AEy6PEbuRiy2Xx3tGywMMrNuNQ08mfvyoEX9J1nxd6iqbJTpieWLHQQwCborXaZXb3aqOA+MpdWJMDV59bHLd0GanqOS6uCFx7O1RrTrj5GYxnHdtFJNg2hr\/CWVHuIX96QNe\/7r9meLTUmuPJFacdT3OojMtRSiUNLVTSzOjYDOxJwe+u4SKSVTjLJQKOQA+oTytuVZcXM6smtMb1Zix1JJieoEUYAhyoI9AMg6myNjximHEf\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475361","version":"1342203709"}'),
    'pe' => array('persona' => '{"id":"475118","name":"Peru Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/8\/475118\/Persona_peru.jpg?1342039555","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/8\/475118\/footer_persona_peru.jpg?1342039555","detailURL":"http:\/\/www.getpersonas.com\/persona\/475118","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/8\/475118\/preview.jpg?1342039555","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/8\/475118\/preview_small.jpg?1342039555","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFQABAQAAAAAAAAAAAAAAAAAACAf\/xAAiEAABBAEEAgMAAAAAAAAAAAADAQIEEQUABhIhCDETIpH\/xAAWAQEBAQAAAAAAAAAAAAAAAAAGBQf\/xAAkEQACAAUDBAMAAAAAAAAAAAABAgADBBEhBhJBBxMxwSNhcf\/aAAwDAQACEQMRAD8Ao\/mXPDvF+2crBAUHwrlopxHS3jIE7BvavBVS7bfv0qaJ6h+RpRtwfUax0vqB2KsqfDKOPI3CCKZkfGGDImDSWwjuQ2BkOFxr3y6Vb1EQKozD+c02YxCm37mGh5PbbjbKgbPxGXkyDSDjykqU4BlpZBijc5GuWlc1to1FXtUba9rqvqDbT9lM2APqAfSynmz5FYxtvZ1Y4xdt5NhwM2H1BHy+HAWa5w3uKO\/or7uv3Rgz7HEa8lBuGRYx\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475118","version":"1342039555"}'),
    'pk' => array('persona' => '{"id":"475358","name":"Flag Pakistan","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/8\/475358\/Persona_pakistan.jpg?1342202813","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/8\/475358\/footer_persona_pakistan.jpg?1342202813","detailURL":"http:\/\/www.getpersonas.com\/persona\/475358","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/8\/475358\/preview.jpg?1342202813","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/8\/475358\/preview_small.jpg?1342202813","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFQABAQAAAAAAAAAAAAAAAAAABgP\/xAAjEAACAgICAgEFAAAAAAAAAAABAgMEBhEABRIhBwgUInGB\/8QAGgEAAQUBAAAAAAAAAAAAAAAAAwABAgQFB\/\/EACMRAAIBBAEDBQAAAAAAAAAAAAECAAMEESESBUFhEyIxccH\/2gAMAwEAAhEDEQA\/AA30\/Y51GY1c9wavY6qll\/fY4sGNPasCFLMq2I5LFZZG0EkmhTwHsbBYb0TzXrHjhu3ecq6XTW4WrbjAdl9vnYJH2RqCvk3EfkXCem6TGs\/wavjT0JbX2qS1o4b1oSMGZ5SGLyopGlY\/iNkKTs8JTZXJKnMpXlC4t0WlXQLjONYJ\/T4gUTXAfORonVh681Pv9cflBekPmQs23aZpGaKV2I9sGO\/6TviBkWQZ3P\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475358","version":"1342202813"}'),
    'ph' => array('persona' => '{"id":"474693","name":"Flag Philippines","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/3\/474693\/Persona_phillipines1.jpg?1341604993","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/3\/474693\/footer_persona_phillipines.jpg?1341604993","detailURL":"http:\/\/www.getpersonas.com\/persona\/474693","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/3\/474693\/preview.jpg?1341604993","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/3\/474693\/preview_small.jpg?1341604993","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQQGCP\/EACMQAAEDAwIHAAAAAAAAAAAAAAEABRECAwQH0RMhMUJRc5P\/xAAZAQACAwEAAAAAAAAAAAAAAAAABwIDBAb\/xAAkEQABAgMIAwAAAAAAAAAAAAAAAQIDBDEFERIWF1ORkhNEVP\/aAAwDAQACEQMRAD8AzwNEmrue8n507rVniZ2m8qNXQazF9yJ1YEaJtgMB5ySPTRujPEztN5UNBbM+yJ1YXVlztGeICSekLirh5eS+g3ZzMaqSbc+OSjQtTE6in\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/474693","version":"1341604993"}'),
    'ro' => array('persona' => '{"id":"475119","name":"Flag of Romania","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/9\/475119\/Persona_romania.jpg?1342039599","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/9\/475119\/footer_persona_romania.jpg?1342039599","detailURL":"http:\/\/www.getpersonas.com\/persona\/475119","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/9\/475119\/preview.jpg?1342039599","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/9\/475119\/preview_small.jpg?1342039599","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFQABAQAAAAAAAAAAAAAAAAAACQj\/xAAhEAABAwMEAwAAAAAAAAAAAAABAgMEAAYxESFCsRITcf\/EABYBAQEBAAAAAAAAAAAAAAAAAAgHCf\/EAB0RAAIDAAIDAAAAAAAAAAAAAAECAAMRBBITUWH\/2gAMAwEAAhEDEQA\/AKcuC34smK4hKANlK0A2xWeXG5hrcEH1LEy9iIa02L6S4lI5HunAjaBL1dR41wRPpT7bjDhwPA5+UD60IYD7IUDpENadHC3FkDke6ddZxREXdUGWf\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475119","version":"1342039599"}'),
    'eg' => array('persona' => '{"id":"475360","name":"Flag of Egypt","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/0\/475360\/Persona_Egypt.jpg?1342203591","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/0\/475360\/footer_persona_egypt.jpg?1342203591","detailURL":"http:\/\/www.getpersonas.com\/persona\/475360","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/0\/475360\/preview.jpg?1342203591","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/0\/475360\/preview_small.jpg?1342203591","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQQFCP\/EACQQAAIBAgUEAwAAAAAAAAAAAAECAxESAAQHCBMFITFRBhSR\/8QAGAEAAwEBAAAAAAAAAAAAAAAAAAUHAgT\/xAAkEQACAQMDAwUAAAAAAAAAAAABAgADESEFBkEEBxIXYYGCkf\/aAAwDAQACEQMRAD8AVfcbsEgN8Onuq8b0uBWeKh9VAzHjCipo9AoRTw1sZ54lQ9Wdyth3Q\/RZK6xuR2O51zMnwPVWIu7Nxw5lI41BPYKv2DT9xnptIRaQFc3bNyMD2xOc90NwgeKuptyUBPyRa\/5MSRvJW4sGBHa7yRhzJ1BJx3GljehQ0wQn\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475360","version":"1342203591"}'),
    'pl' => array('persona' => '{"id":"475404","name":"Poland Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/0\/4\/475404\/Persona_poland.jpg?1342218317","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/0\/4\/475404\/footer_persona_poland.jpg?1342218317","detailURL":"http:\/\/www.getpersonas.com\/persona\/475404","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/0\/4\/475404\/preview.jpg?1342218317","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/0\/4\/475404\/preview_small.jpg?1342218317","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABQYH\/8QAIhAAAAUDBAMAAAAAAAAAAAAAAQIDBREABCEGCBIyNHGy\/8QAGAEAAwEBAAAAAAAAAAAAAAAAAwUHAgb\/xAAhEQACAQIGAwAAAAAAAAAAAAABAgADBAUHQpGS0URSVP\/aAAwDAQACEQMRAD8AvXjdk2XRjRoRwAeXKAcU59daSDGEOg7yttlXcU\/JXge4ItutaZEptBOATjz05+a0MWX0O8A2WFx9S8T3MYukgNiIGudUy71qZMLVtAyEZogaL2pEmf\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475404","version":"1342218317"}'),
    'be' => array('persona' => '{"id":"475236","name":"Belgium Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/6\/475236\/Persona_belgium.jpg?1342126038","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/6\/475236\/footer_persona_belgium2.jpg?1342126038","detailURL":"http:\/\/www.getpersonas.com\/persona\/475236","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/6\/475236\/preview.jpg?1342126038","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/6\/475236\/preview_small.jpg?1342126038","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIG\/8QAHhAAAgICAgMAAAAAAAAAAAAAAQIRIQADBAUSMVL\/xAAYAQACAwAAAAAAAAAAAAAAAAADBAUHCP\/EABwRAAICAwEBAAAAAAAAAAAAAAABAgMRIUEEUf\/aAAwDAQACEQMRAD8APlNohlRj5e4qMopRNgylrZnu0ZgrJANE3jtK+kV6pZWEy9vZr9RgVW+DM7l0Da55K0xNHDRyhaxxez\/\/2Q==","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475236","version":"1342126038"}'),
    'fr' => array('persona' => '{"id":"475014","name":"Flag of France","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/4\/475014\/Persona_france2.jpg?1341943037","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/4\/475014\/footer_persona_france.jpg?1341943037","detailURL":"http:\/\/www.getpersonas.com\/persona\/475014","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/4\/475014\/preview.jpg?1341943037","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/4\/475014\/preview_small.jpg?1341943037","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABQQG\/8QAHBAAAgEFAQAAAAAAAAAAAAAAAQIRAAMEEiEF\/8QAGAEAAgMAAAAAAAAAAAAAAAAABAUDBwj\/xAAcEQACAgIDAAAAAAAAAAAAAAAAAQIhAwQREjH\/2gAMAwEAAhEDEQA\/AMzk2rMMtvbYdMxFVMjb86VgHpI6hk1UiJ7RWJCbcdUNs6kHsUGqH0uslZHlYrX1gMTU8JMXbGGPvB\/\/2Q==","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475014","version":"1341943037"}'),
    'dk' => array('persona' => '{"id":"475405","name":"Flag of Denmark","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/0\/5\/475405\/Persona_denmark.jpg?1342218900","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/0\/5\/475405\/footer_persona_denmark.jpg?1342218900","detailURL":"http:\/\/www.getpersonas.com\/persona\/475405","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/0\/5\/475405\/preview.jpg?1342218900","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/0\/5\/475405\/preview_small.jpg?1342218900","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAACAQH\/8QAJxAAAQEHAwMFAAAAAAAAAAAAAQIDBAUGBxIhAAgREyJRIzEyQXT\/xAAYAQACAwAAAAAAAAAAAAAAAAAFBwABBv\/EACwRAAECBAIHCQAAAAAAAAAAAAECAwAEESEFBgcSFSIxYdEyQUNTcaGisdP\/2gAMAwEAAhEDEQA\/AFzRChktyI4zewhFVIXMAjUMDo8NHYMrXJFrUdRdrVWO8nNvxOfAaRkm5cLCXAqo5W484a2b82zmMuya35JbJaXrAK1t81TYVSL27q8Yy1G0inyUISncjLaglIHNrvnH6ND9ks+ePbrG3OkvFSSdkOfP84j2g3IgFVUMrgowBPJAHA7Hj31MI7D3p1i9KFTNYXU+KftEG93ZKDBn6YHaPoeNAxSG+SupvH\/\/2Q==","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475405","version":"1342218900"}'),
    'de' => array('persona' => '{"id":"474687","name":"Flag - Germany","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/7\/474687\/Persona_germany2.jpg?1341604484","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/7\/474687\/footer_persona_germany2.jpg?1341604484","detailURL":"http:\/\/www.getpersonas.com\/persona\/474687","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/7\/474687\/preview.jpg?1341604484","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/7\/474687\/preview_small.jpg?1341604484","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQYHCP\/EACIQAAIBBAEEAwAAAAAAAAAAAAECAwAEBxEFBhIhMghxkf\/EABcBAAMBAAAAAAAAAAAAAAAAAAAEBgX\/xAAhEQAABQMFAQAAAAAAAAAAAAAAAQIDBQQykQYxQtHScf\/aAAwDAQACEQMRAD8AxjdZi+Phcm0xn1QEI9ZOQttg\/YSptNJN8nkYV2LpWp4k9o1rB+gu8vk3EV4jCz6E52IH17r2A6\/EplFPKlc6nB9hF2ej3LaFsvhH6EoihMZDMispGwG35rbEmBO8QY9qRsSfA0dUAH\/\/2Q==","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/474687","version":"1341604484"}'),
    'hu' => array('persona' => '{"id":"475237","name":"Flag of Hungary","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/7\/475237\/Persona_hungary2.jpg?1342126292","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/7\/475237\/footer_persona_hungary.jpg?1342126292","detailURL":"http:\/\/www.getpersonas.com\/persona\/475237","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/7\/475237\/preview.jpg?1342126292","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/7\/475237\/preview_small.jpg?1342126292","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABAYH\/8QAIxAAAQIFBAMBAAAAAAAAAAAAAQIDAAQIESEGEiJBJlGSof\/EABoBAAEFAQAAAAAAAAAAAAAAAAEAAgMEBgf\/xAAiEQACAAQGAwAAAAAAAAAAAAAAAQIRU6IEBhMUGNMhMZH\/2gAMAwEAAhEDEQA\/AKJ7XtOzRCl0ySguL8dVTeR8xj9xhKNzJOQubk56rs6w7mv6cwlKxS9L9g+VzmfyBuMJQuYuReb6r+QdZmYS6OS1BQIxu7EUfJwSb9h3g2FY2q9CxtAGuKTmf\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475237","version":"1342126292"}'),
    'hk' => array('persona' => '{"id":"475662","name":"Flag of Hong Kong","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/2\/475662\/Persona_hongkong2.jpg?1342475786","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/2\/475662\/footer_persona_hongkong.jpg?1342475786","detailURL":"http:\/\/www.getpersonas.com\/persona\/475662","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/2\/475662\/preview.jpg?1342475786","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/2\/475662\/preview_small.jpg?1342475786","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABwID\/8QAJBAAAgEDAwMFAAAAAAAAAAAAAQIDBAURABIhIjFRBgcIE2H\/xAAZAQACAwEAAAAAAAAAAAAAAAADBAUGBwj\/xAAjEQACAQQBAwUAAAAAAAAAAAABAhEAAxIhMQVRgQQGE0Fh\/9oADAMBAAIRAxEAPwBG+SNLPbPcWKnr\/TFqssKW6E0a0MCoKmnIIEkmFTr3KwwUXb25AB1m\/WwyepxZAogRA5Hc8b8arp72E9u\/0s3bV97hLnLIk4t2EltQQZyM86OqJZW3YYHjxjUJNXwJ91pJca2taE3CrlqvohSCEzyM5SJc7UXPZRk4A4GToz5tBYzGvFJWvhtStpQskkwAJJ5J\/T3qHeEnoKN4HOP3QTqm0OQr\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475662","version":"1342475786"}'),
    'br' => array('persona' => '{"id":"474692","name":"Flag Brazil","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/2\/474692\/Persona_brazil1c.jpg?1341604936","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/2\/474692\/footer_persona_brazil.jpg?1341604936","detailURL":"http:\/\/www.getpersonas.com\/persona\/474692","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/2\/474692\/preview.jpg?1341604936","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/2\/474692\/preview_small.jpg?1341604936","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABwUG\/8QAJRAAAQMDAwMFAAAAAAAAAAAAAQIDBAUGEQASIQcTQSIyYXGB\/8QAGAEAAgMAAAAAAAAAAAAAAAAABgcBBAX\/xAAmEQABAwIGAgIDAAAAAAAAAAABAgMRAAQFBhIhMUFhgQhRFCJx\/9oADAMBAAIRAxEAPwC90IitRbZrtehRHaVAlPtFURbpXHbeSk73G3DztKSkEK5Tgeo+F98gH2F4nY2iiHLhKVyQP20KI0BQHchREciTAqrkROm1efSChskbE7AgGSCeoiZ4+zQr1pqXTydUHXLfaLtVKz3JELCY6jnnf4WflP6TqMlWuYLdpIvjpZjZK5K\/EdpHhXoUG5yusu3ClfhCXp3UjZHmeifKfZNae+L7ua8GEU2S5HgUdlO2NSoDXYiNJ8AIT7vtWdEOD5YscIdVdDU7cK3U64dbij96jx6ilzi2b8UxwBDyghkcNoGlAH8HPsmjOVRmlOkpCVc8DBxoirJF4U1\/\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/474692","version":"1341604936"}'),
    'jp' => array('persona' => '{"id":"474688","name":"Flag Japan","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/8\/474688\/Persona_japan_1.jpg?1341604546","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/8\/474688\/footer_persona_JAPAN.jpg?1341604546","detailURL":"http:\/\/www.getpersonas.com\/persona\/474688","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/8\/474688\/preview.jpg?1341604546","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/8\/474688\/preview_small.jpg?1341604546","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAAAgMJ\/8QAHxAAAgICAQUAAAAAAAAAAAAAAQIAEQMSQQQTITFx\/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP\/EABQRAQAAAAAAAAAAAAAAAAAAAAD\/2gAMAwEAAhEDEQA\/ANR2XVtgxB58wA12GFmAn6jDZUvXHqBLu4DeuQMfsD\/\/2Q==","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/474688","version":"1341604546"}'),
    'ma' => array('persona' => '{"id":"475116","name":"Flag of Morocco","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/6\/475116\/Persona_morocco.jpg?1342039379","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/6\/475116\/footer_persona_morocco.jpg?1342039379","detailURL":"http:\/\/www.getpersonas.com\/persona\/475116","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/6\/475116\/preview.jpg?1342039379","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/6\/475116\/preview_small.jpg?1342039379","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFQABAQAAAAAAAAAAAAAAAAAABgf\/xAAgEAEAAgICAQUAAAAAAAAAAAABAgMAEQQhBRIiQUJh\/8QAGQEAAgMBAAAAAAAAAAAAAAAAAwcCBAUG\/8QAIhEAAgEDBAIDAAAAAAAAAAAAAQIRAAMEBRITIQYiMVFx\/9oADAMBAAIRAxEAPwCEeZSne6aY+0X0q7\/couVgE901vC9F1jH1fJwsd2wOBLHLb3c\/Ix5PcNcG2HMuGUtEkSG3ACuc2NhKMSPaaB7wfVN67vD\/ADNUbmcWye2aSJH2+TAg12uTjWWcuF9oiY7iSYn6kk\/pNHuV4iptWJGXfRp1k91ZZ08Oa\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475116","version":"1342039379"}'),
    'kr' => array('persona' => '{"id":"475368","name":"South Korea Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/8\/475368\/Persona_southkorea.jpg?1342204122","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/8\/475368\/footer_persona_southkorea.jpg?1342204122","detailURL":"http:\/\/www.getpersonas.com\/persona\/475368","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/8\/475368\/preview.jpg?1342204122","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/8\/475368\/preview_small.jpg?1342204122","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAABQYHCP\/EACMQAAIBAgYCAwAAAAAAAAAAAAECAwYRAAQFEhMhByIjQVH\/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAf\/EABURAQEAAAAAAAAAAAAAAAAAAAAB\/9oADAMBAAIRAxEAPwDfniulKBpHXql0+jqgczrmVGa0VZ7Q6Z6qdiRffsT8nd77b9HBaozX3XFz1ghfpOh6TocZiOn8oYeY7Q0jcjRRA3WFHb2EQYswUk2LtgDvLCb7XDd\/uA\/\/2Q==","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475368","version":"1342204122"}'),
    'kz' => array('persona' => '{"id":"475241","name":"Kazakhastan Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/1\/475241\/Persona_kazakhastan.jpg?1342126636","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/1\/475241\/footer_persona_kazakhastan.jpg?1342126636","detailURL":"http:\/\/www.getpersonas.com\/persona\/475241","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/1\/475241\/preview.jpg?1342126636","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/1\/475241\/preview_small.jpg?1342126636","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABgUH\/8QAIhAAAgEDAwUBAAAAAAAAAAAAAQIDBAURABITBiExQZFx\/8QAGAEAAgMAAAAAAAAAAAAAAAAABAYCBQj\/xAAmEQABAwMDBAIDAAAAAAAAAAABAgMRAAQhBRIxBhNBUSIyQmHB\/9oADAMBAAIRAxEAPwCr15Q2W11st9tUlOtJX1c6wxLKQ21AuWYDxncMffenToPV7y8tU6ZqCT3mWm1LV+JKyobRPO3aZ9ccg1m7qOzt7d43drHbcWoJE5hMZMe5\/vmsn6guEvIjRIqAk9lJOfun1wlPFLzKUryRTK63yC61ImqaSTjVNkMfMxEaZztXOSRkk5JJPvQOlaUzpLJZa+xMqVABUqIkhIAGMAAAAYAqd7eKvVhxYwOBJwPQmT+8kk+TRy4U9BPKTCgKjwG7\/urQI3jNAlwtn41\/\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475241","version":"1342126636"}'),
    'sa' => array('persona' => '{"id":"475363","name":"Saudi Arabia Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/3\/475363\/Persona_saudi-arabia.jpg?1342203819","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/3\/475363\/footer_persona_saudiarabia.jpg?1342203819","detailURL":"http:\/\/www.getpersonas.com\/persona\/475363","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/3\/475363\/preview.jpg?1342203819","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/3\/475363\/preview_small.jpg?1342203819","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFQABAQAAAAAAAAAAAAAAAAAABwb\/xAAhEAACAQQCAgMAAAAAAAAAAAABAgMABAUREiEHMRNBQv\/EABkBAAEFAAAAAAAAAAAAAAAAAAABBAUGCP\/EACARAAIBAwQDAAAAAAAAAAAAAAACAQMEERIUMUEhIpH\/2gAMAwEAAhEDEQA\/AD\/yPn5MrLAZrbGL8MbENZluLcyCQ2wPRHrXW6XgzjUutwyq0L4jrPfwJr5pTKGVQvZGhugfU9OngTL60eTZchgR+vujJV6LOvtkm7rDRNKSoVu+ho6oJCLyVP\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475363","version":"1342203819"}'),
    'my' => array('persona' => '{"id":"475362","name":"Flag of Malaysia","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/2\/475362\/Persona_malaysia.jpg?1342203763","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/2\/475362\/footer_persona_malaysia.jpg?1342203763","detailURL":"http:\/\/www.getpersonas.com\/persona\/475362","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/2\/475362\/preview.jpg?1342203763","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/2\/475362\/preview_small.jpg?1342203763","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAABQYHCP\/EACMQAAEDBAIBBQAAAAAAAAAAAAECAwYABAUREhMhYYGDstL\/xAAYAQACAwAAAAAAAAAAAAAAAAADBwABBP\/EACYRAAAEBAQHAAAAAAAAAAAAAAACAwQBkdHSERIxQRMkUVNio6T\/2gAMAwEAAhEDEQA\/ANMrdhtm8bhCY+lRTslLmD4n2DVL4sW0NMk0bQ5jFfG14snN4TJVk8EHkG0bwQSSd6GDOwfiohE0D6ZJo2gSqrxPuyc3CuC2l3HXTJyPVuR\/qi4OvP31GeMWHVL5KAfe4CSXRHZaydWj42zIyPtU5mGx5L1FYMI7pTaUH\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475362","version":"1342203763"}'),
    'mx' => array('persona' => '{"id":"475115","name":"Flag of Mexico","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/5\/475115\/Persona_mexico-1.jpg?1342039329","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/5\/475115\/footer_persona_mexico.jpg?1342039329","detailURL":"http:\/\/www.getpersonas.com\/persona\/475115","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/5\/475115\/preview.jpg?1342039329","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/1\/5\/475115\/preview_small.jpg?1342039329","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFQABAQAAAAAAAAAAAAAAAAAABwb\/xAAgEAABBAMAAgMAAAAAAAAAAAABAgMEEQAFIRIxQXGB\/8QAFwEAAwEAAAAAAAAAAAAAAAAAAwUGCP\/EACERAAICAQIHAAAAAAAAAAAAAAECABEDBBIFEyIxQVHh\/9oADAMBAAIRAxEAPwAs3m20qYz7UmCpbrh8kOtyFUn8JFj7GRaMvmbM1mnzhg6NQ9UPsJ56ll4rAqyfV9w4qooyF93eIcyK45ZWQoKHPL5xepIlzqsaP0gSelaloukpCFd4KNYfm1E54dvM\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475115","version":"1342039329"}'),
    'se' => array('persona' => '{"id":"475120","name":"Sweden Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/2\/0\/475120\/Persona_Sweden.jpg?1342039759","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/2\/0\/475120\/footer_persona_SW.jpg?1342039759","detailURL":"http:\/\/www.getpersonas.com\/persona\/475120","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/2\/0\/475120\/preview.jpg?1342039759","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/2\/0\/475120\/preview_small.jpg?1342039759","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFQABAQAAAAAAAAAAAAAAAAAABwH\/xAAoEAABAgQEBQUAAAAAAAAAAAABAgMEBQYHAAgRIhITITJBMTNhkcP\/xAAYAQEAAwEAAAAAAAAAAAAAAAAHAgMEBv\/EACkRAAECBAMIAwEAAAAAAAAAAAECAwAEBREGB0ESISIxMlGBwUJF0tP\/2gAMAwEAAhEDEQA\/AEup7T0\/H2lpqilXCgYFqUuhxMz4UhqK93akcwDXf4Ue36KaPj2bkMWz1cTT1rU8mxaBO0jo3ngJ+OqRzi+o4UYmqBK0tU2lKWjcLNrK6tw4gNe55QHVFl6kMO+AzdyWOpJ12spH7YRE5uT7wuaO6PKv5xygy+lW\/sEHwP3EuDPFOZbqFhgpKkpiR3H10S\/8Y04ZKkZi1V2\/NPtuIVtG1g+Qb7K9LgFcmEGl8KW2h3cCeh6jyMMhcKtYOQ3s6R\/\/2Q==","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475120","version":"1342039759"}'),
    'at' => array('persona' => '{"id":"475239","name":"Austria Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/9\/475239\/Persona_austria2.jpg?1342126489","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/9\/475239\/footer_persona_austria2.jpg?1342126489","detailURL":"http:\/\/www.getpersonas.com\/persona\/475239","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/9\/475239\/preview.jpg?1342126489","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/3\/9\/475239\/preview_small.jpg?1342126489","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFQABAQAAAAAAAAAAAAAAAAAABAb\/xAAnEAABAgUCBQUAAAAAAAAAAAABAgQAAwUREgdRBggTISIjQWGBof\/EABgBAAMBAQAAAAAAAAAAAAAAAAIEBgMI\/8QAKhEAAgAEAwUJAAAAAAAAAAAAAQIAAwQRBQYhEhMxgZIUFiJTVHORobH\/2gAMAwEAAhEDEQA\/AHp1j0ROPV5a6OoFNrS+JH3Y\/dog+20nkDqMdjd08zKTs4w\/OTLgLjV3RDPw5WqGtPsVcSPr\/hNoE1lJ6cdRjdctZmC641Mv7MqIZpSW86mznIpT5U+WoDPL00\/JNxttCQUFb2MVUyodJwTeLsn55cf2B1Q06cA3bMU9bDznKcKWchskAAX27wLFToBDVMs1fE7aX4WA+9TH\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475239","version":"1342126489"}'),
    'fi' => array('persona' => '{"id":"475648","name":"Flag Finland","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/8\/475648\/Persona_finland.jpg?1342470757","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/8\/475648\/footer_persona_finland.jpg?1342470757","detailURL":"http:\/\/www.getpersonas.com\/persona\/475648","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/8\/475648\/preview.jpg?1342470757","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/8\/475648\/preview_small.jpg?1342470757","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAABQYHCP\/EACcQAAECBAUDBQAAAAAAAAAAAAECBAMFBhIABwgRIRMiMTIzNFFx\/8QAGAEAAwEBAAAAAAAAAAAAAAAABQYHAQP\/xAAnEQABAgQFAwUAAAAAAAAAAAABAgMABBEhBQYxNMESkdITQlFhcv\/aAAwDAQACEQMRAD8AbdReoeq8wJrQr+f5NTimIkhmpetITqK43mC74J6KLoKDd2JHF3qHH3TMHwhmUQ8lt8L6hQ0pbW+p4iXYzi704tlTjBQUmorW+ltB8fcUOea3c14kTjS1VbfdRBSpTrf8+KOcC0ZalAN2k9vKDKsyzijtFDv4wd16QlIqfJUXqIVVCx3qJPutfGOeVSPSmvxwqNzWkh2Uv7+UxrJ3L1uCVKUsi8kDc+N8J4UBDkQY\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475648","version":"1342470757"}'),
    'gr' => array('persona' => '{"id":"475649","name":"Flag of Greece","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/9\/475649\/Persona_greece.jpg?1342470919","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/9\/475649\/footer_persona_greece.jpg?1342470919","detailURL":"http:\/\/www.getpersonas.com\/persona\/475649","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/9\/475649\/preview.jpg?1342470919","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/4\/9\/475649\/preview_small.jpg?1342470919","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABAUH\/8QAJxAAAQIFAwMFAQAAAAAAAAAAAQIEAwUGBxEACBIXIUETFVFxodL\/xAAXAQADAQAAAAAAAAAAAAAAAAABAwcC\/8QAKREAAQIFAQYHAAAAAAAAAAAAAQIDAAQFERKTFDJBQlPRITFRUqGx0v\/aAAwDAQACEQMRAD8A1W8FP2afbkJ4t3NoM2qSI2amPJKjd+zybgGUEJWX6F8wsI4qCeOColPjOqTTHZ9FKRinFFzZSBmvePKRa1+Pp4xNakzTl1Zeasl2F0qOKd0c17+XzA1UDbNRybVWDIznPVpz3\/dM2yc6z+gIzsVP6TOse8InFzKQqB\/EnFQ3W2+zR64CfUdPbau40WIEpCU5WoEnCQAPgADxoNSEwykIaZfSBwDqQILtQlH1FbrrClHiWiT9ROVW1sj26g7b\/rpY5\/nTBKTnTmNYd4XtUh72NE\/mP\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475649","version":"1342470919"}'),
    'ua' => array('persona' => '{"id":"475656","name":"Flag of Ukraine","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/6\/475656\/Persona_ukraine.jpg?1342474461","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/6\/475656\/footer_persona_ukraine.jpg?1342474461","detailURL":"http:\/\/www.getpersonas.com\/persona\/475656","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/6\/475656\/preview.jpg?1342474461","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/6\/475656\/preview_small.jpg?1342474461","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABgMI\/8QAJBAAAQMDAgcBAAAAAAAAAAAAAQIDBAAFEQYIExYhMVFkstL\/xAAaAQABBQEAAAAAAAAAAAAAAAAHAQMEBQYI\/8QAJhEAAQMBBwQDAAAAAAAAAAAAAQACAwQFBwgRITHSEkSCg5KT0f\/aAAwDAQACEQMRAD8AnO2oXVkY52h4HpLB+6HgxQUEm1mP+1vBZpt2U7e6b8DyQu\/bd7rBe4SNXR158Q1\/qp0WIqjqR1Cz3D2N4JRd1KzeoB8T+rcV2tQWVJCOvauLIJ8tUXC1EJ+k2pTmVtgkGreKvLBomizNf\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475656","version":"1342474461"}'),
    'no' => array('persona' => '{"id":"475658","name":"Flag of Norway","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/8\/475658\/Persona_norway.jpg?1342474901","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/8\/475658\/footer_persona_norway.jpg?1342474901","detailURL":"http:\/\/www.getpersonas.com\/persona\/475658","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/8\/475658\/preview.jpg?1342474901","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/8\/475658\/preview_small.jpg?1342474901","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABgQF\/8QAJBAAAQQBBAICAwAAAAAAAAAAAwECBAUGABESISRRE6EUMWL\/xAAYAQACAwAAAAAAAAAAAAAAAAAFBgMEB\/\/EACgRAAECBQIFBQEAAAAAAAAAAAECBAADBREhBjEHEkGBkRMiM2Gh4f\/aAAwDAQACEQMRAD8Ajmy67GZbJUk+B4VJkiFPZGo6I+TWgxnG0w\/JnubEEqsI1U4J1unrUTlemaFOVJMlU2Yk5vgXjZKa24i66aIcpciU3WMEKCbgY2QCo7Zv1g7kmc4zemYa5qMkzmQHoZ81yEpgM9cIMP4QsT+eTk1Sna7coHIwlIlD6FzDDTuBjTm9Sru1zVbkJ9o8quT4EBbPILG5q8eifgqOXTU4ag8kxeSSGgeRAvRqdt2C4TFRVXsfrQTUD9rVKgt3IBAVbBte8OmgqHVdM0ZNMclKiFKIIvYA5t0vm57xnNhzip5M4uy\/to9mJ9d\/egnOkbCHQN58z5Jh7Y\/v7H\/\/2Q==","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475658","version":"1342474901"}'),
    'sg' => array('persona' => '{"id":"475659","name":"Flag of Singapore","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/9\/475659\/Persona_singapore.jpg?1342474967","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/9\/475659\/footer_persona_singapore.jpg?1342474967","detailURL":"http:\/\/www.getpersonas.com\/persona\/475659","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/9\/475659\/preview.jpg?1342474967","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/5\/9\/475659\/preview_small.jpg?1342474967","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAACAMG\/8QAJBAAAgEDAwMFAAAAAAAAAAAAAQIDBAURACExBgdBCBITMnL\/xAAYAQADAQEAAAAAAAAAAAAAAAAABgcEBf\/EACYRAAECBQIGAwAAAAAAAAAAAAEAAgMEERIhBTEGByJBYZFysdH\/2gAMAwEAAhEDEQA\/AFVc+xXVtzqZZrwlnrHqnWSqqZK1xNLOVYe4P8OUjyRlN\/rjPGOM7T4jzV9DXfOa+tvCq0DjeQlGBssXttw0BgtDag5F+XYPV5WVuXpC6zroQ8VRYIpDw63CcqR+THrI7Rorh29n8TPL81dNguyIhHwb93JiGCmVCiFVG+wXz50yKBKD01OVAD5xwNCF\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475659","version":"1342474967"}'),
    'sk' => array('persona' => '{"id":"475660","name":"Flag of Slovakia","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/0\/475660\/Persona_slovakia.jpg?1342475070","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/0\/475660\/footer_persona_slovakia.jpg?1342475070","detailURL":"http:\/\/www.getpersonas.com\/persona\/475660","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/0\/475660\/preview.jpg?1342475070","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/6\/0\/475660\/preview_small.jpg?1342475070","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFQABAQAAAAAAAAAAAAAAAAAABgX\/xAAlEAABAwIFBAMAAAAAAAAAAAABAgMEBREABggSIRMxYXEHFDL\/xAAZAQACAwEAAAAAAAAAAAAAAAADBwQFBgj\/xAApEQACAAUDAgUFAAAAAAAAAAABAgADBBEhBQYSIoEHExVBUTJhkcHR\/9oADAMBAAIRAxEAPwBo\/qUz18fPPy8g1uOIFYWZzLFTDskNM2SB021uL6QUsumwURYJtxbETTq7T9MebK1aXM5Xwoxx+bhjcG\/t8Q5txbC1fekmlqttTqcIqEPMORMJPSVaWlmAUC5IBuc5vAzMetvUc4pDqKzl9sEqTZFIT+fZOLb1\/bR+mTN7kf2Mk3gtviUbPV03bn+0gA6Z7r65cuR9gvC+58kqWPdu3Hbxhbu7zGLubk+5yT3jr+RT01NJWmpkCKuAFACr9gBgRGqMaGp0qAZdN+E7VbfOB8rHEHFL5q9Vx+I\/\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475660","version":"1342475070"}'),
    'il' => array('persona' => '{"id":"475785","name":"Israel Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/5\/475785\/Persona_israel2.jpg?1342560041","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/5\/475785\/footer_persona_israel.jpg?1342560041","detailURL":"http:\/\/www.getpersonas.com\/persona\/475785","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/5\/475785\/preview.jpg?1342560041","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/5\/475785\/preview_small.jpg?1342560041","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEAZABkAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAACAQH\/8QAKRAAAQMDAQUJAAAAAAAAAAAAAgEDEQQGBwAFEyEnQQgJEhciM0Rh0\/\/EABcBAAMBAAAAAAAAAAAAAAAAAAIFBgT\/xAApEQABAgMFCAMAAAAAAAAAAAABAAQCA5EFEyFCkhESFDFRU9HhUmGC\/9oADAMBAAIRAxEAPwBMv4u7uGmZdOkq8VA6rZEKDdYDKxw+SnCY6pqjDu2zzEen0kRbWSMRu6vayKz7G7HVXSVrl9bNxVSvC+G4Ru5GwklFd8I7uucQmhc9LRrCmEEsqumU6faUJF0Yz+aZRjs59CsMqSxIN4Ia1zHDp9Ju+SWIV8XKizSVUhFLYFJw+vb1K8c57kVT5VAGckZBQKR\/BOIXI5TWYkL0t+k\/PRB+47kWo+UJZyfgKBf\/2Q==","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475785","version":"1342560041"}'),
    'ie' => array('persona' => '{"id":"475786","name":"Flag of Ireland","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/6\/475786\/Persona_ireland.jpg?1342560551","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/6\/475786\/footer_persona_ireland.jpg?1342560551","detailURL":"http:\/\/www.getpersonas.com\/persona\/475786","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/6\/475786\/preview.jpg?1342560551","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/6\/475786\/preview_small.jpg?1342560551","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFQABAQAAAAAAAAAAAAAAAAAABgf\/xAAgEAACAQQCAwEAAAAAAAAAAAABAhEAAwUhBBITMUGB\/8QAFwEBAQEBAAAAAAAAAAAAAAAAAwQHCP\/EABwRAAMAAwADAAAAAAAAAAAAAAABAgMREiExgf\/aAAwDAQACEQMRAD8AveQ5WPRXN20e77DrdMD8muZlmxcuanf0294762mC8yFjyCNg+vtDAlCnlJLFWE6jdSR0vJRWvQfyHDS6SqdTBgCqJtSwXG0f\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475786","version":"1342560551"}'),
    'nz' => array('persona' => '{"id":"475787","name":"New Zealand Flag","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/7\/475787\/Persona_n_zealand.jpg?1342560598","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/7\/475787\/footer_persona_n-zealand.jpg?1342560598","detailURL":"http:\/\/www.getpersonas.com\/persona\/475787","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/7\/475787\/preview.jpg?1342560598","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/7\/475787\/preview_small.jpg?1342560598","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAABAUGCP\/EACQQAAIBBAAFBQAAAAAAAAAAAAECAwAEESEFEiIjMTJBUWGx\/8QAGAEAAwEBAAAAAAAAAAAAAAAAAgUHAAH\/xAAjEQACAQMEAgMBAAAAAAAAAAABEQIAEjEDEyFBBBQyUXHB\/9oADAMBAAIRAxEAPwDOzXtnaMJmWL0g9E7jK\/GB4\/KtOxaJHTCJZxw\/s\/05qTHy5a0oDyZGUYoZZER1F4QaGKlOPXqvOHtoxHGXYqASSR7ZyfNCN2MI7quXKw+0+V+0Wv6x19T1btpm25XW9XLhrK4eKYqk69x2Dqw1zZ2PrVMTb8aWKSu6oG7igZyQI33oYOK4dISHNYaltf\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475787","version":"1342560598"}'),
    'ae' => array('persona' => '{"id":"475788","name":"Flag of UAE","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/8\/475788\/Persona_UAE.jpg?1342560708","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/8\/475788\/footer_persona_UAE.jpg?1342560708","detailURL":"http:\/\/www.getpersonas.com\/persona\/475788","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/8\/475788\/preview.jpg?1342560708","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/8\/475788\/preview_small.jpg?1342560708","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAABAUGCP\/EACcQAAIABQIEBwAAAAAAAAAAAAECAAMHEiEEEQUGCAkTIkFCYXGi\/8QAFwEAAwEAAAAAAAAAAAAAAAAAAAEEBv\/EACIRAAEBBwUBAAAAAAAAAAAAAAACAQMFBxFhkRQVIpLhMf\/aAAwDAQACEQMRAD8AbNXbt76ZvGQ1SUsLiEkgbj6DxDoHN8mFZLeCpZTn28JbmOvXQg8xG4bIqiFzdfpxn9wbe5vkaZcQVPxi+3hhsCcPO7Bgw93qPiLjfA09ZV5IsbOBsdoVAP\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475788","version":"1342560708"}'),
    'za' => array('persona' => '{"id":"475789","name":"Flag of South Africa","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/9\/475789\/Persona_s-africa.jpg?1342560786","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/9\/475789\/footer_persona_s_africa.jpg?1342560786","detailURL":"http:\/\/www.getpersonas.com\/persona\/475789","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/9\/475789\/preview.jpg?1342560786","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/8\/9\/475789\/preview_small.jpg?1342560786","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABgQH\/8QAJhAAAQMDAwIHAAAAAAAAAAAAAQIDBAUGERITIQAxBxQWI0FRov\/EABgBAAIDAAAAAAAAAAAAAAAAAAUHAAMG\/8QAKxEAAQIFAQYGAwAAAAAAAAAAAQIEAAMFESFBBhITMVGBIjIzUmGxkaHR\/9oADAMBAAIRAxEAPwCKpSrips70xZNeckQUxRKqUWetmRT4CgPc3Fq1MKS2eC6lKQTwnJxkBR5rx9LHGl2UTgC+Rod0i6b+03I1hNNZzqh1QsdmXi1pAyeSR1zcpIGqgACcC8ZzcF0uPnZq\/ivUZbAyPLUWC4hkj6GvZR+T1r5ezz1eF2T3\/kG5qHr7xP3qln43j97o\/UMq5WJUy3WLVixI8GmoIdkoZKtc98dnX1nlenshAwhHwMkqIplUprAHgABR1Iue18D8Qt2lZcNG4bt0pSnmTzKj1JPTQDA0F8wAk2\/G3SUNtnnjg9SdU3bj1JhPe31Fi6s4X51kx\/\/Z","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475789","version":"1342560786"}'),
    'ru' => array('persona' => '{"id":"475791","name":"Flag of Russia","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/1\/475791\/Persona_russia3b.jpg?1342561549","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/1\/475791\/footer_persona_russia2.jpg?1342561549","detailURL":"http:\/\/www.getpersonas.com\/persona\/475791","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/1\/475791\/preview.jpg?1342561549","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/1\/475791\/preview_small.jpg?1342561549","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQMEB\/\/EACcQAAECAggHAAAAAAAAAAAAAAECAwAHBAUGCBEhUYESE0GFkaGi\/8QAGgEAAQUBAAAAAAAAAAAAAAAAAQADBAUGCP\/EACURAAECBAQHAAAAAAAAAAAAAAEAAgMFEZIEBgcSFSExQUSD0f\/aAAwDAQACEQMRAD8AU5eunysjG3VGT21k4fMSuPSI+K+8K+OmGaWdZhBPrcrWL1s7ENZzIq8nRypWstwIInki74eJcE2dN81Vo3GwbXfFhLyKQFYKbKdSenmMKDRdAxGlyPJdKQSrh39wtyAgEc1\/\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475791","version":"1342561549"}'),
    'ir' => array('persona' => '{"id":"475795","name":"Flag of Iran","category":null,"description":"","author":"MozThemes","username":"mozthemes","headerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/5\/475795\/Persona_iran2.jpg?1342565097","footerURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/5\/475795\/footer_persona_iran.jpg?1342565097","detailURL":"http:\/\/www.getpersonas.com\/persona\/475795","previewURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/5\/475795\/preview.jpg?1342565097","iconURL":"http:\/\/getpersonas-cdn.mozilla.net\/static\/9\/5\/475795\/preview_small.jpg?1342565097","dataurl":"data:image\/png;base64,\/9j\/4AAQSkZJRgABAQEASABIAAD\/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD\/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD\/wAARCAAQABADAREAAhEBAxEB\/8QAFgABAQEAAAAAAAAAAAAAAAAABQQH\/8QAIxAAAQIGAQUBAAAAAAAAAAAAAgEhAAMEBQcRCAYyQVGh0v\/EABoBAAEFAQAAAAAAAAAAAAAAAAUBAgMGBwj\/xAAlEQABAgMHBQAAAAAAAAAAAAABAAIDBBEFCCFDodPhBhVCgqL\/2gAMAwEAAhEDEQA\/AFizjgpimcW7OrbbqOr\/ADFY7u0ZevC2Bl1jpzxjfB3EZcc54SERGn4tWQR2vdf6ovqjDha7Tl68JIl1+wIWAjV9DuLD6SrInUkJFRt+YDObRdKy8y14AVBDKmFpRRfTNEdaIg1ofgQv\/9k=","accentcolor":null,"textcolor":null,"updateURL":"https:\/\/www.getpersonas.com\/en-US\/update_check\/475795","version":"1342565097"}')
);

// Sort by key
ksort($personas);

// Detect if the user is viewing the page with Firefox.
// TODO: Detect Firefox version?
$is_firefox = strpos($_SERVER['HTTP_USER_AGENT'], 'Firefox') !== false;
?>
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">

    <!-- Use style tag due to css file issues on getpersonas. -->
    <style>
/* http://meyerweb.com/eric/tools/css/reset/
   v2.0 | 20110126
   License: none (public domain)
*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header, hgroup,
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
    margin: 0;
    padding: 0;
    border: 0;
    font-size: 100%;
    font: inherit;
    vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure,
footer, header, hgroup, menu, nav, section {
    display: block;
}
body {
    line-height: 1;
}
ol, ul {
    list-style: none;
}
blockquote, q {
    quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
    content: '';
    content: none;
}
table {
    border-collapse: collapse;
    border-spacing: 0;
}

/* For modern browsers */
.clearfix:before,
.clearfix:after {
    content:"";
    display:table;
}
.clearfix:after {
    clear:both;
}
/* For IE 6/7 (trigger hasLayout) */
.clearfix {
    zoom:1;
}

@font-face {
    font-family: 'Open Sans';
    src: url('fonts/OpenSans-Italic-webfont.eot');
    src: url('fonts/OpenSans-Italic-webfont.eot?#iefix') format('embedded-opentype'),
         url('fonts/OpenSans-Italic-webfont.woff') format('woff'),
         url('fonts/OpenSans-Italic-webfont.ttf') format('truetype'),
         url('fonts/OpenSans-Italic-webfont.svg#OpenSansRegular') format('svg');
    font-weight: normal;
    font-style: italic;
}

@font-face {
    font-family: 'Open Sans Light';
    src: url('fonts/OpenSans-Light-webfont.eot');
    src: url('fonts/OpenSans-Light-webfont.eot?#iefix') format('embedded-opentype'),
         url('fonts/OpenSans-Light-webfont.woff') format('woff'),
         url('fonts/OpenSans-Light-webfont.ttf') format('truetype'),
         url('fonts/OpenSans-Light-webfont.svg#OpenSansLight') format('svg');
    font-weight: normal;
    font-style: normal;
}

body {
    background: url("images/bg.png") #e3e9ee repeat;
    color: #484848;
}

a {
    color: #2983c8;
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}

#container {
    background: url("images/header-bg.jpg") no-repeat;
    min-height: 670px;
}

#show-us-msg,
#customize-msg,
#callout-msg {
    text-shadow: #fafafa 1px 1px 1px;
}

#show-us-msg {
    font-family: 'Open Sans Light', sans-serif;
    font-weight: normal;
    font-size: 68px;
    letter-spacing: -1px;
    margin: 0 auto;
    padding-top: 40px;
    text-align: center;
    width: 580px;
}

#cauldron {
    background: url('images/cauldron.png') no-repeat;
    float: right;
    height: 441px;
    margin: 0 50px -150px -50px;
    width: 403px;
}

#customize-msg {
    font-family: 'Open Sans Light', sans-serif;
    font-weight: normal;
    font-size: 28px;
    margin: 60px 0 0 80px;
    position: relative;
    width: 340px;
}

#callout-msg {
    font-family: 'Open Sans', sans-serif;
    font-size: 18px;
    font-style: italic;
    font-weight: normal;
    margin: 30px 0 0 80px;
    position: relative;
}

.arrow {
    background: url('images/arrow.png');
    display: inline-block;
    height: 14px;
    vertical-align: bottom;
    width: 17px;
}

#personas {
    background: transparent;
    background: rgba(197, 197, 197, 0.24);
    box-shadow: 1px 1px 0 rgba(255, 255, 255, 0.9), inset 0px 0px 3px rgba(0, 0, 0, 0.01), inset 0px 0px 3px rgba(0, 0, 0, 0.03);
    clear: both;
    margin: 50px auto 0;
    padding: 20px 15px;
    position: relative;
    width: 740px;
}

#personas li {
    float: left;
    height: 100px;
    margin: 0 10px;
    width: 165px;
}

#personas img {
    cursor: pointer;
    width: 165px;
}

#personas span {
    font-family: 'Open Sans Light', sans-serif;
    font-size: 16px;
}

#fan-box {
    background: #FFFFFF;
    box-shadow: 1px 1px rgba(0, 0, 0, 0.05);
    margin: 50px auto 20px;
    min-height: 90px;
    position: relative;
    width: 770px;
}

#fan-box img {
    bottom: 0;
    position: absolute;
    left: 0;
}

#see-all-msg {
    bottom: 20px;
    font-family: 'Open Sans', sans-serif;
    font-size: 18px;
    font-style: italic;
    font-weight: normal;
    position: absolute;
    right: 20px;
    text-align: right;
    width: 210px;
}
    </style>
  </head>
  <body>
    <div id="container">
      <div id="show-us-msg"><?php echo ___('Show your support!'); ?></div>
      <div id="cauldron"></div>
      <div id="customize-msg"><?php echo ___('Customize Firefox with your nation\'s flag and join us in celebrating the global spirit of community.'); ?></div>
      <div id="callout-msg">
        <?php if ($is_firefox): ?>
          <?php echo ___('Roll over to try, click to apply.'); ?> <i class="arrow"></i>
        <?php else: ?>
          <a href="https://mozilla.org/firefox/"><?php echo ___('Download Firefox to try or apply these themes.'); ?></a>
        <?php endif; ?>
      </div>

      <div id="personas">
        <ol class="clearfix">
          <?php foreach ($personas as $id => $data): ?>
            <li>
              <img src="images/previews/<?php echo $id; ?>.jpg" persona="<?php echo $data['persona']; ?>">
              <span><?php echo get_region_name($id); ?></span>
            </li>
          <?php endforeach; ?>
        </ol>
      </div>

      <div id="fan-box">
        <img src="images/browser-stack.png">
        <div id="see-all-msg">
          <a href="https://addons.mozilla.org/firefox/collections/mozilla/flags/" target="_parent"><?php echo ___('See more Firefox Themes »'); ?></a>
        </div>
      </div>
    </div>
    <script>
(function() {
  var aliases = {'PreviewPersona': 'PreviewBrowserTheme',
           'ResetPersona': 'ResetBrowserThemePreview',
           'SelectPersona': 'InstallBrowserTheme'};
  var persona_previews = document.querySelectorAll('#personas img');

  for (var k = 0; k < persona_previews.length; k++) {
    var item = persona_previews[k];
    item.setAttribute('data-browsertheme', item.getAttribute('persona'));

    item.addEventListener('mouseover', preview_mouseover, false);
    item.addEventListener('mouseout', preview_mouseout, false);
    item.addEventListener('click', preview_click, false);
  }

  function preview_mouseover(e) {
    dispatch_persona_event('PreviewPersona', e.target);
  }

  function preview_mouseout(e) {
    dispatch_persona_event('ResetPersona', e.target);
  }

  function preview_click(e) {
    dispatch_persona_event('SelectPersona', e.target);
  }

  function dispatch_persona_event(event, preview_node) {
    dispatch_event(event, preview_node);
    if (event in aliases) {
      dispatch_event(aliases[event], preview_node);
    }
  }

  function dispatch_event(event, aNode) {
    var eventObject = document.createEvent("Events");
    eventObject.initEvent(event, true, false);
    aNode.dispatchEvent(eventObject);
  }
})();
    </script>
  </body>
</html>